# Generated by Django 4.2.1 on 2023-07-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("products", "0001_initial"),
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitemdiscount",
            name="max_amount_product_in_cart",
        ),
        migrations.RemoveField(
            model_name="cartitemdiscount",
            name="max_total_price_of_cart",
        ),
        migrations.RemoveField(
            model_name="cartitemdiscount",
            name="min_amount_product_in_cart",
        ),
        migrations.RemoveField(
            model_name="cartitemdiscount",
            name="min_total_price_of_cart",
        ),
        migrations.RemoveField(
            model_name="cartitemdiscount",
            name="products_group_1",
        ),
        migrations.RemoveField(
            model_name="cartitemdiscount",
            name="products_group_2",
        ),
        migrations.AddField(
            model_name="cartitemdiscount",
            name="amount_product_in_cart",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Скидка может быть установлена на количество товаров в корзине.",
                null=True,
                verbose_name="Минимальное количество товаров в корзине",
            ),
        ),
        migrations.AddField(
            model_name="cartitemdiscount",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s",
                to="catalog.catalog",
                verbose_name="категории товаров",
            ),
        ),
        migrations.AddField(
            model_name="cartitemdiscount",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s",
                to="products.product",
                verbose_name="товары",
            ),
        ),
        migrations.AddField(
            model_name="cartitemdiscount",
            name="total_price_of_cart",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Скидка может быть установлена на стоимость товаров в корзине.",
                max_digits=10,
                null=True,
                verbose_name="Минимальная цена товаров в корзине",
            ),
        ),
        migrations.AlterField(
            model_name="cartitemdiscount",
            name="description",
            field=models.TextField(max_length=150, verbose_name="Описание скидки"),
        ),
        migrations.AlterField(
            model_name="cartitemdiscount",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="размер скидки"),
        ),
        migrations.AlterField(
            model_name="shopitemdiscount",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s",
                to="catalog.catalog",
                verbose_name="категории товаров",
            ),
        ),
        migrations.AlterField(
            model_name="shopitemdiscount",
            name="description",
            field=models.TextField(max_length=150, verbose_name="Описание скидки"),
        ),
        migrations.AlterField(
            model_name="shopitemdiscount",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="размер скидки"),
        ),
        migrations.AlterField(
            model_name="shopitemdiscount",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s",
                to="products.product",
                verbose_name="товары",
            ),
        ),
    ]
