# Generated by Django 4.2.1 on 2023-07-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_browsing_history_options_and_more'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemdiscount',
            name='active',
            field=models.BooleanField(verbose_name='скидка активна'),
        ),
        migrations.AlterField(
            model_name='cartitemdiscount',
            name='description',
            field=models.TextField(max_length=150, verbose_name='описание скидки'),
        ),
        migrations.AlterField(
            model_name='cartitemdiscount',
            name='max_amount_product_in_cart',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальное количество товаров в корзине'),
        ),
        migrations.AlterField(
            model_name='cartitemdiscount',
            name='max_total_price_of_cart',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='максимальная цена товаров в корзине'),
        ),
        migrations.AlterField(
            model_name='cartitemdiscount',
            name='min_amount_product_in_cart',
            field=models.PositiveIntegerField(blank=True, help_text='скидка может быть установлена на количество товаров в корзине.', null=True, verbose_name='минимальное количество товаров в корзине'),
        ),
        migrations.AlterField(
            model_name='cartitemdiscount',
            name='min_total_price_of_cart',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='скидка может быть установлена на стоимость товаров в корзине.', max_digits=10, null=True, verbose_name='минимальная цена товаров в корзине'),
        ),
        migrations.AlterField(
            model_name='cartitemdiscount',
            name='products_group_1',
            field=models.ManyToManyField(blank=True, help_text='скидка может быть установлена на группу товаров, если они вместе находятся в корзине. Указывается группа товаров 1 и группа товаров 2.', related_name='cart_item_discounts_group_1', to='products.product', verbose_name='группа товаров 1'),
        ),
        migrations.AlterField(
            model_name='shopitemdiscount',
            name='active',
            field=models.BooleanField(verbose_name='скидка активна'),
        ),
        migrations.AlterField(
            model_name='shopitemdiscount',
            name='description',
            field=models.TextField(max_length=150, verbose_name='описание скидки'),
        ),
    ]
