# Generated by Django 4.2.1 on 2023-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitemdiscount',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='shop_items_discounts', to='products.product', verbose_name='товары'),
        ),
        migrations.AddField(
            model_name='cartitemdiscount',
            name='products_group_1',
            field=models.ManyToManyField(blank=True, help_text='Скидка может быть установлена на группу товаров, если они вместе находятся в корзине. Указывается группа товаров 1 и группа товаров 2.', related_name='cart_item_discounts_group_1', to='products.product', verbose_name='группа товаров 1'),
        ),
        migrations.AddField(
            model_name='cartitemdiscount',
            name='products_group_2',
            field=models.ManyToManyField(blank=True, related_name='cart_item_discounts_group_2', to='products.product', verbose_name='группа товаров 2'),
        ),
    ]
