# Generated by Django 4.2.1 on 2023-07-17 05:54

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Browsing_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'просмотр продута',
                'verbose_name_plural': 'просмотр продуктов',
                'ordering': ['-data_at'],
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, verbose_name='имя файла или URL для импорта')),
                ('start_time', models.DateTimeField(null=True, verbose_name='дата и время начала импорта')),
                ('end_time', models.DateTimeField(null=True, verbose_name='дата и время окончания импорта')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('running', 'В процессе выполнения'), ('completed', 'Выполнен'), ('failed', 'Завершен с ошибкой')], default='pending', max_length=10, verbose_name='статус импорта')),
                ('imported_count', models.IntegerField(default=0, verbose_name='количество импортированных товаров')),
                ('errors', models.JSONField(default=list, verbose_name='список ошибок при импорте')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email получателя уведомления')),
                ('task_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='идентификатор задачи')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='наименование')),
                ('limited_edition', models.BooleanField(default=False, verbose_name='ограниченный тираж')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='индекс сортировки')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=products.models.product_preview_directory_path, verbose_name='предварительный просмотр')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.product_images_directory_path, verbose_name='изображение')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'изображения продуктов',
                'verbose_name_plural': 'изображение продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, verbose_name='значение')),
            ],
            options={
                'verbose_name': 'свойство продукта',
                'verbose_name_plural': 'свойства продуктов',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'свойство',
                'verbose_name_plural': 'свойства',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='оценка')),
                ('review_text', models.TextField(max_length=500, null=True, verbose_name='текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
