# Generated by Django 4.2.1 on 2023-05-24 07:19

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='наименование')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=products.models.product_preview_directory_path, verbose_name='предварительный просмотр')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'свойство',
                'verbose_name_plural': 'свойства',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, verbose_name='значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.property')),
            ],
            options={
                'verbose_name': 'свойство продукта',
                'verbose_name_plural': 'свойства продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.product_images_directory_path, verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='продукт', to='products.product')),
            ],
            options={
                'verbose_name': 'изображения продуктов',
                'verbose_name_plural': 'изображение продукта',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='property',
            field=models.ManyToManyField(through='products.ProductProperty', to='products.property', verbose_name='характеристики'),
        ),
    ]
