# Generated by Django 4.2.1 on 2023-05-15 15:00

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_preview_directory_path, verbose_name='предварительный просмотр'),
        ),
    ]
