# Generated by Django 4.2.1 on 2023-05-15 15:34

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.product_images_directory_path, verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='продукт', to='products.product')),
            ],
            options={
                'verbose_name': 'Изображения продуктов',
                'verbose_name_plural': 'Изображение продукта',
            },
        ),
    ]
