# Generated by Django 4.2.1 on 2023-07-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='deal_of_the_day',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='express_shipping_price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=6, verbose_name='стоимость экспресс-доставки, $'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='free_shipping_min_order_amount',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=6, verbose_name='минимальная сумма заказа для бесплатной доставки, $'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='standard_shipping_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6, verbose_name='стандартная цена доставки, $'),
        ),
    ]
