# Generated by Django 4.2.1 on 2023-07-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name="цена"),
        ),
    ]
