# Generated by Django 4.2.1 on 2023-07-17 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='orderstatuschange',
            name='dst_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_order_change_dst', to='shops.orderstatus'),
        ),
        migrations.AddField(
            model_name='orderstatuschange',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.order'),
        ),
        migrations.AddField(
            model_name='orderstatuschange',
            name='src_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_order_change_src', to='shops.orderstatus'),
        ),
        migrations.AddField(
            model_name='orderoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.offer'),
        ),
        migrations.AddField(
            model_name='orderoffer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ManyToManyField(related_name='orders', through='shops.OrderOffer', to='shops.offer', verbose_name='предложение'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shops.orderstatus', verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='products.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.shop'),
        ),
    ]
