# Generated by Django 4.2.1 on 2023-07-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0002_alter_offer_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="цена"),
        ),
    ]
