# Generated by Django 4.2.1 on 2023-07-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_orderstatus_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='citi',
            new_name='city',
        ),
    ]
