# Generated by Django 4.2.1 on 2023-07-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_order_pay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderoffer',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='orderoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.offer', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='orderoffer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
    ]
