# Generated by Django 4.2.1 on 2023-07-28 10:22

from django.db import migrations, models
import shops.models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0005_alter_orderoffer_options_alter_orderoffer_offer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentqueue",
            name="card_number",
            field=models.IntegerField(validators=[shops.models.validate_card_number], verbose_name="номер карты"),
        ),
    ]
