# Generated by Django 4.2.1 on 2023-08-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="slug",
            field=models.SlugField(blank=True, max_length=256, verbose_name="slug"),
        ),
    ]
